gorm:
  driverName: mysql
  ipAddr: 192.168.56.130
  port: 3306
  username: root
  password: amdin
  database: rush_mall
  maxOpenConn: 100
  maxIdeConn: 100
  # 7 * 24 * 60 * 60
  connMaxLifetime: 604800
  params: ?charset=utf8&parseTime=true